### ISSUE TITLE
Does not work anymore when upgrading dependencies

### ISSUE THREAD

**Issue by rsaccon** [developit/preact-compat-example#2]
After exploring MDL I wanted to give react-toolbox + preact-compat a try. Unfortunately things started to fall apart when upgrading the dependencies. First I upgraded preact and preact-compat. At that point, ripple effect did not work anymore, when checking I go this: 
`Uncaught TypeError: Cannot read property 'ripple' of undefined`

and things got worse when updating react-toolbox, the button style did not get applied anymore, and on clicking the button I got this
`Uncaught TypeError: Cannot read property 'button' of undefined`

I tried to follow the code changes in react-toolbox button between then and now, there are many, but my understanding of the internals of react, preact and react-toolbox at this time is unfortunatly not sufficient to fix those issues!

**Comment by developit** [comment]
Looking into this now, thanks for the tip!

**Comment by rsaccon** [comment]
I just checked whether the deep-going changes in preact 4 made this example magically work again, but as halfway expected, this is not the case. I guess preact-compat needs some overhaul. @developit, what are your plans in regard to preact-compat ?

**Comment by developit** [comment]
Yup, I have some stuff locally, I will push when I get a second today - thanks for the reminder.  I was just waiting until the refs support got into preact proper, which is done now.

**Comment by rsaccon** [comment]
it looks a bit better now with `preact-compat 1.0.0` (the ripple effect seems to work now), but something is still messed up with the button in the example:
`Uncaught TypeError: r.refs.button.blur is not a function`

**Comment by developit** [comment]
I just published `preact@beta` (`4.1.0`) and `preact-compat@beta` (`1.1.0`) that together fix this issue :)
About to publish the updated preact-compat-example, and then I want to try out a bunch more of react-toolbox.  React compatibility with these two new versions should be vastly improved!

**Comment by developit** [comment]
Published!

**Comment by rsaccon** [comment]
great, thanks a lot, gonna play with this now

**Comment by developit** [comment]
I just backported all the updates from `react-toolbox-example`, probably good to pull that. They stopped bundling the icon font and a few other changes.
