### ISSUE TITLE
Some react-toolbox components work, some not

### ISSUE THREAD

**Issue by rsaccon** [developit/preact-compat-example#3]
I just tried them all to see how far we get with preact-4.1.0 and preact-compat-1.1.0

First the good news: Many (if not most) components just work as expected.

Now the bad news.  The following imports fail:

```
import DatePicker from 'react-toolbox/lib/date_picker';
import { List, ListItem, ListSubHeader, ListDivider, ListCheckbox } from 'react-toolbox';
import {IconMenu, MenuItem, MenuDivider } from 'react-toolbox';
import { RadioGroup, RadioButton } from 'react-toolbox';
import { Snackbar } from 'react-toolbox';
import {Tab, Tabs} from 'react-toolbox';
import TimePicker from 'react-toolbox/lib/time_picker';
```

The error is always the same: `ReactCSSTransitionGroup` module cannot be resolved and/or polyfill modules cannot be resolved. Here is an example of such an error:

```
./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/array/from' in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
resolve module core-js/fn/array/from in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
  looking for modules in /Users/robertosaccon/preact-compat-example/node_modules
    /Users/robertosaccon/preact-compat-example/node_modules/core-js doesn't exist (module as directory)
[/Users/robertosaccon/preact-compat-example/node_modules/core-js]
 @ ./~/react-toolbox/lib/utils/polyfills.js 3:0-32


./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/array/iterator' in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
resolve module core-js/fn/array/iterator in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
  looking for modules in /Users/robertosaccon/preact-compat-example/node_modules
    /Users/robertosaccon/preact-compat-example/node_modules/core-js doesn't exist (module as directory)
[/Users/robertosaccon/preact-compat-example/node_modules/core-js]
 @ ./~/react-toolbox/lib/utils/polyfills.js 5:0-36


./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/map' in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
resolve module core-js/fn/map in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
  looking for modules in /Users/robertosaccon/preact-compat-example/node_modules
    /Users/robertosaccon/preact-compat-example/node_modules/core-js doesn't exist (module as directory)
[/Users/robertosaccon/preact-compat-example/node_modules/core-js]
 @ ./~/react-toolbox/lib/utils/polyfills.js 7:0-25


./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/string/starts-with' in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
resolve module core-js/fn/string/starts-with in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
  looking for modules in /Users/robertosaccon/preact-compat-example/node_modules
    /Users/robertosaccon/preact-compat-example/node_modules/core-js doesn't exist (module as directory)
[/Users/robertosaccon/preact-compat-example/node_modules/core-js]
 @ ./~/react-toolbox/lib/utils/polyfills.js 9:0-40


./~/react-toolbox/lib/utils/polyfills.js
Module not found: Error: Cannot resolve module 'core-js/fn/symbol' in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
resolve module core-js/fn/symbol in /Users/robertosaccon/preact-compat-example/node_modules/react-toolbox/lib/utils
  looking for modules in /Users/robertosaccon/preact-compat-example/node_modules
    /Users/robertosaccon/preact-compat-example/node_modules/core-js doesn't exist (module as directory)
[/Users/robertosaccon/preact-compat-example/node_modules/core-js]
 @ ./~/react-toolbox/lib/utils/polyfills.js 11:0-28


./~/react-addons-css-transition-group/index.js
Module not found: Error: Cannot resolve module 'preact-compat/lib/ReactCSSTransitionGroup' in /Users/robertosaccon/preact-compat-example/node_modules/react-addons-css-transition-group
resolve module preact-compat/lib/ReactCSSTransitionGroup in /Users/robertosaccon/preact-compat-example/node_modules/react-addons-css-transition-group
  looking for modules in /Users/robertosaccon/preact-compat-example/node_modules
    resolve 'file' or 'directory' lib/ReactCSSTransitionGroup in /Users/robertosaccon/preact-compat-example/node_modules/preact-compat
      resolve file
        /Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup doesn't exist
        /Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup.jsx doesn't exist
        /Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup.scss doesn't exist
        /Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup.js doesn't exist
        /Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup.json doesn't exist
      resolve directory
        /Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup doesn't exist (directory default file)
        /Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup/package.json doesn't exist (directory description file)
[/Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup]
[/Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup.jsx]
[/Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup.scss]
[/Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup.js]
[/Users/robertosaccon/preact-compat-example/node_modules/preact-compat/lib/ReactCSSTransitionGroup.json]
 @ ./~/react-addons-css-transition-group/index.js 1:17-61
```

The CSS transition stuff has been mentioned before: https://github.com/developit/preact-compat/issues/14. Now I am wondering whether preact-compat should be extended or instead just a specific toolbox compatibility layer created

The following components don't work as expected or throw runtime errors at initial render:

**Avatar**: Inline SVG (Github Icon in the original documentation example) does not get displayed

**Dialog** and **Drawer**: throw a runtime error
`Uncaught TypeError: Cannot read property 'map' of undefined`

**DropDown**: throws a runtime error
`Uncaught Error: Invalid prop`value`of type`number`supplied to`Dropdown`, expected`string`.`

Would be great if we get all components working !!!

**Comment by developit** [comment]
Hmm - those `core-js` imports just mean you need to `npm install babel-runtime` (I didn't have it installed). The other ones might be solvable via a wrapper, but ultimately I would love to have this work just with the single alias setup (I know it's a lofty goal haha). 
Thanks for the list though, will be looking at this ASAP.

**Comment by rsaccon** [comment]
I installed the babel runtime, nothing changed. Does it need to be configured at the webpack config file ?

**Comment by developit** [comment]
Ah, apologies, I meant [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/). It includes `core-js`. Also, make sure you're using Babel 6, since it looks like react-toolbox requires it.

**Comment by rsaccon** [comment]
Also with `babel-poyfill` installed, the polyfill modules cannot be resolved. You mean Babel 6.0.x ? I have the original preact-compat-example babel version (6.5.x), but the released react toolbox documentation example has 6.2.x / 6.3.x

**Comment by developit** [comment]
Hmm, just any 6 should be fine. I can't understand why they would be relying on core-js directly, rather than going through babel-polyfill... Maybe manually install `core-js`? Also what version of `npm` are you running?  `3.x` may cause issues with react-toolbox.

**Comment by rsaccon** [comment]
Ok, thanks. Directly installing `core-js` sorted out the polyfill issue. Now all the import failures (still same list) are just the CSS transition thing.

**Comment by rsaccon** [comment]
About the Dialog and Drawer Components, the error message above is wrong (I messed ip somethign in my setup). However they do not render, because toolbox calls `React.DOM.noscript()`. This just creates a `noscript` tag. I experimented with some hack:

```
if (!React.DOM) {
  React.DOM = {};
}
if (!React.DOM.noscript) {
  React.DOM.noscript = function(){
    return document.createElement('noscript');
  };
}
```

and with this now Dialog and Drawer work perfectly as well.

**Comment by developit** [comment]
Ah that reminds me: preact-compat needs to be exporting those built-in tag methods. Easy fix!

**Comment by developit** [comment]
@rsaccon `preact-compat` now supports all HTML elements as `React.DOM.*()` factories, which fixes the `React.DOM.noscript()` issue you found.  I guess that just leaves `ReactCSSTransitionGroup` ;)

**Comment by developit** [comment]
@rsaccon Any chance you can publish your tests? I want to check if aliasing `react-addons-css-transition-group` to `rc-css-transition-group` (https://github.com/react-component/css-transition-group/) fixes the issue, or start on a reimplementation.

**Comment by rsaccon** [comment]
@developit `preact-compat 1.2.0` unfortunately does not solve the noscript issue. I get the following error:
`Uncaught TypeError: _react2.default.DOM.noscript is not a function`

The CSS thing is still the same as well, with  `preact-compat 1.2.0` 

My "tests" is or was just copy pasted snippets from the toolbox documentation into the current preact-compat-example. But I will later try to port the whole toolbox documentation to preact, that I guess would be a nice example

**Comment by developit** [comment]
@rsaccon Ah sorry, I was rushing and made a very silly error. Just published `1.2.1` with the correction.
A ported docs would be seriously amazing.

**Comment by rsaccon** [comment]
the aliasing works:

alias: {
  'react': 'preact-compat',
  'react-dom': 'preact-compat',
  'react-addons-css-transition-group': 'rc-css-transition-group'
}

however the homepage to rc-css-transition-group says it is deprecated  in favor of https://github.com/react-component/animate

my testing so far: **List** works now, 

**Menu**, does not show any  menu, 

**Snackbar** causes this error:
`Uncaught TypeError: _this.refs.snackbar.show is not a function`

**DatePicker** and **TimePicker** do not work
`Uncaught TypeError: Cannot read property 'getFullYear' of undefined`
`Uncaught TypeError: Cannot read property 'getHour' of undefined`

**Tabs** does not work:
`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined`

**RadioGroup** does not work:
`Uncaught TypeError: Cannot read property 'value' of undefined`
at the stackstrace the error is at:
`checked: radio.props.value === _this2.props.value,`

btw. thanks precat-compat 1.2.1, that sorts out the noscript issue

(need some sleep now, later I will try to port the docs)

**Comment by rsaccon** [comment]
One of the things which don't work yet with react toolbox is inline svg. I guess it might work if I just use `preact-svg`and its `SVG` component. Or should preact-compat make preact handle native svg html tags (as it seems to happen with react) ?

**Comment by developit** [comment]
I think it would be reasonable to have `preact-compat` pull in `preact-svg` in order to get parity here.
Would just be [here](https://github.com/developit/preact-compat/blob/master/src/index.js#L105):

```
import SVG from 'preact-svg';
// ...
if (vnode.nodeName==='svg') {
  vnode.nodeName = SVG;
}
```

**Comment by rsaccon** [comment]
Ah, thanks, I tried it, but something still gets messed up:  if I check a rendered svg node with the chrome dev tools, I see:
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" class="circle__3isa4">[object Object]</svg>`
(while in the working react-toolbox demo I see there the actual svg tag soup)

**Comment by developit** [comment]
Funky. Might be a bug in preact-svg, will look into this.

**Comment by rsaccon** [comment]
Ups, after correcting the snippet

```
import SVG from 'preact-svg';
// ...
if (vnode.nodeName==='svg') {
  vnode.nodeName = 'SVG';
}
```

the svg is all there, when Inspecting with chrome dev tools, but it remains invisible

**Comment by rsaccon** [comment]
@developit, did you had a chance to look into the issues, why some of the components do not work ? I could not figure out yet ...

**Comment by developit** [comment]
@rsaccon yup, found and fixed the SVG issue, looking into the others now. Update for the demo coming soon (I fixed the links so they go through preact-router).

I think the time picker issue is related to this:
https://github.com/react-toolbox/react-toolbox/pull/332

It seems like the authors of react-toolbox were relying on some coincidental semantics around the timing of lifecycle events, but they have been going through and fixing that.  There has not been a release since that fix (and the others like it) were merged, so we're sortof waiting on them.

**Comment by rsaccon** [comment]
thanks a lot. Ah yes, I saw that issue on the react-toolbox, where the main developer mentioned to cut a new release soonish, 12 days ago.

**Comment by developit** [comment]
That's soon~ish, haha.  I might have trampled on your PR btw, sorry (was tweaking and didn't push).
_Edit_: just published the updated demo.

**Comment by developit** [comment]
Think we should close this issue?  Most stuff works now (except datepicker, no clue what's going on there).

**Comment by rsaccon** [comment]
Yeah, most works. It would be unrealistic to expect that everything always will work exactly as with react

**Comment by developit** [comment]
I think once libs start depending on React 15 compatibility will be less of an issue.  The issues we saw tended to come from some of the lesser known older React APIs (the deprecated/undocumented stuff).
